version: 2

updates:

  # SCA : surveille les dépendances Dart/Flutter (pubspec.yaml)
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "security"

  # Surveille aussi les actions GitHub utilisées dans vos workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"